data: /home/mlx/ai-ml/datasets/
output: ${oc.env:SCRATCH}/aifs/

logs:
  base: ${hardware.paths.output}/logs
  wandb: ${hardware.paths.logs.base}
  mlflow: ${hardware.paths.logs.base}/mlflow
  tensorboard: ${hardware.paths.logs.base}/tensorboard

checkpoints: ${hardware.paths.output}checkpoint
plots: ${hardware.paths.output}plots
profiler: ${hardware.paths.output}profiler
graph: /home/mlx/data/graphs/